# SPDX-License-Identifier: GPL-2.0
#
# Makefile for linux/drivers/siengine
#

obj-$(CONFIG_SE1000_ROOTFS_LOAD_SYNC) += rootfs_load_sync/
obj-$(CONFIG_SE1000_DRM_SHMEM) += drm_mem/
obj-$(CONFIG_SE1000_EFUSE) += efuse/
