# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SIENGINE) += se1000_evb.dtb
dtb-$(CONFIG_ARCH_SIENGINE) += se1000_evb_ap1.dtb
dtb-$(CONFIG_ARCH_SIENGINE) += se1000_aibay.dtb
dtb-$(CONFIG_ARCH_SIENGINE) += se1000_aibay_ap1.dtb
dtb-$(CONFIG_ARCH_SIENGINE) += se1000_aibay_ddr-2x4g.dtb
