#ifndef __SIENGINE_RPMSG_ID_H__
#define __SIENGINE_RPMSG_ID_H__

/* 0-255 for rpmsg */

/* 0x400-0x500 for system in future */
#define	SELINK_RPMSG_ID_PMIC_EVB_MAX20411	0x400
#define	SELINK_RPMSG_ID_PMIC_EVB_MPQ5472	0x401
#define	SELINK_RPMSG_ID_PMIC_EVB_MPQ7920	0x402
#define	SELINK_RPMSG_ID_PMIC_DS_DA9063L		0x403
#define	SELINK_RPMSG_ID_FUNC_TEST			0x410
#define	SELINK_RPMSG_ID_DMA_DYN				0x411
#define	SELINK_RPMSG_ID_POWER				0x412
#define	SELINK_RPMSG_ID_PWR_TIMER			0x413
#define	SELINK_RPMSG_ID_TS_ALARM			0x420

/* 0x500-0x600 for selink sub functions */
#define	SELINK_RPMSG_ID_SELINK_DMA			0x500
#define	SELINK_RPMSG_ID_SELINK_MEM			0x501

#define	SELINK_RPMSG_ID_ETHERNET_SEND		0x502
#define	SELINK_RPMSG_ID_ETHERNET_ACK		0x503

/* 0x600-0x700 for muti media sub functions */
/* 0x600~0x61F for Dual SE1000 Sharing ids */
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC0_IPC_PIPE0	0x600
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC0_IPC_PIPE1	0x601
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC0_SELINK_PIPE0	0x602
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC0_SELINK_PIPE1	0x603
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC1_IPC_PIPE0	0x604
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC1_IPC_PIPE1	0x605
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC1_SELINK_PIPE0	0x606
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC1_SELINK_PIPE1	0x607
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_VICAM0	0x608
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_VICAM1	0x609
#define MULTIMEDIA_RPMSG_ID_SHARING_IPC_AGENT0	0x60a
#define MULTIMEDIA_RPMSG_ID_SHARING_IPC_AGENT1	0x60b
#define MULTIMEDIA_RPMSG_ID_SHARING_SELINK_AGENT0	0x60c
#define MULTIMEDIA_RPMSG_ID_SHARING_SELINK_AGENT1	0x60d
#define MULTIMEDIA_RPMSG_ID_SHARING_CP_VICAM0		0x60e
#define MULTIMEDIA_RPMSG_ID_SHARING_CP_VICAM1		0x60f
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_CONTROL_SELINK			0x610
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_GLOBAL_SERVICE_SELINK		0x611
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_TOUCH_INFO0			0x612
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_TOUCH_INFO1			0x613
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_VIRTUAL_TOUCH_INFO0_FROM_CP	0x614
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_VIRTUAL_TOUCH_INFO0_FROM_AP	0x615
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_VIRTUAL_TOUCH_INFO0_AGENT_IPC	0x616
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_VIRTUAL_TOUCH_INFO1_FROM_CP	0x617
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_VIRTUAL_TOUCH_INFO1_FROM_AP	0x618
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_VIRTUAL_TOUCH_INFO1_AGENT_IPC	0x619
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_VIRTUAL_TOUCH_AGENT_INFO0	0x61a
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_VIRTUAL_TOUCH_AGENT_INFO1	0x61b
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_GLOBAL_SERVICE_IPC		0x61c
#define MULTIMEDIA_RPMSG_ID_SHARING_CP_CONTROL_IPC			0x61d
#define MULTIMEDIA_RPMSG_ID_SHARING_CP_VIRTUAL_TOUCH_INFO0_FROM_AGENT	0x61e
#define MULTIMEDIA_RPMSG_ID_SHARING_CP_VIRTUAL_TOUCH_INFO1_FROM_AGENT	0x61f

/* 0x620 ~ 0x634 for clock control */
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_M4	0x620
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_GDC0	0x621
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_GDC1	0x622
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_ISP0	0x623
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_ISP1	0x624
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS0	0x625
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS1	0x626
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS2	0x627
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS3	0x628
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS4	0x629
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS5	0x62a
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS6	0x62b
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS7	0x62c
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS_PHY0	0x62d
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS_PHY1	0x62e
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS_PHY2	0x62f
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS_PHY3	0x630
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS_PHY4	0x631
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS_PHY5	0x632
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS_PHY6	0x633
#define MULTIMEDIA_RPMSG_ID_CLK_CONTROL_CIS_PHY7	0x634

/* 0x640~0x65F for Single SE1000 Sharing ids */
#define MULTIMEDIA_RPMSG_ID_SE04_DISPLAY_AP_PRODUCER	0x640    /* ap to cp screen sharing producer */
#define MULTIMEDIA_RPMSG_ID_SE04_DISPLAY_CP_CONSUMER	0x641    /* ap to cp screen sharing consumer */
#define MULTIMEDIA_RPMSG_ID_SE04_DISPLAY_AP_CONSUMER	0x642    /* cp to ap screen sharing consumer */
#define MULTIMEDIA_RPMSG_ID_SE04_DISPLAY_CP_PRODUCER	0x643    /* cp to ap screen sharing  prodecuer */
#define MULTIMEDIA_RPMSG_ID_SE04_TOUCH_AP_PRODUCER	0x644    /* ap to cp touch producer */
#define MULTIMEDIA_RPMSG_ID_SE04_TOUCH_CP_CONSUMER	0x645    /* ap to cp touch consumer */
#define MULTIMEDIA_RPMSG_ID_SE04_TOUCH_AP_CONSUMER	0x646    /* cp to ap touch consumer */
#define MULTIMEDIA_RPMSG_ID_SE04_TOUCH_CP_PRODUCER	0x647    /* cp to ap touch producer */
#define MULTIMEDIA_RPMSG_ID_SE04_APP_AP_CHN1	0x648    /* ap to cp application communication channel screen share app */
#define MULTIMEDIA_RPMSG_ID_SE04_APP_CP_CHN1	0x649    /* ap to cp application communication channel weston screen share client */
#define MULTIMEDIA_RPMSG_ID_SE04_APP_AP_CHN2	0x64a    /* cp to ap application communication channel AVM app */
#define MULTIMEDIA_RPMSG_ID_SE04_APP_CP_CHN2	0x64b    /* cp to ap application communication channel QT NormalAVM */
#define MULTIMEDIA_RPMSG_ID_SE04_APP_AP_CHN3	0x64c    /* cp to ap application communication channel ap avm service */
#define MULTIMEDIA_RPMSG_ID_SE04_APP_CP_CHN3	0x64d    /* cp to ap application communication channel QT FastAVM */

/* BOOTANIMATION */
#define MULTIMEDIA_RPMSG_ID_BOOTANIMATION_AP_KERNEL_CHN0	0x64e
#define MULTIMEDIA_RPMSG_ID_BOOTANIMATION_CP_KERNEL_CHN0	0x64f
#define MULTIMEDIA_RPMSG_ID_BOOTANIMATION_AP_KERNEL_CHN1	0x650
#define MULTIMEDIA_RPMSG_ID_BOOTANIMATION_CP_KERNEL_CHN1	0x651
#define MULTIMEDIA_RPMSG_ID_BOOTANIMATION_AP_KERNEL_CHN2	0x652
#define MULTIMEDIA_RPMSG_ID_BOOTANIMATION_CP_KERNEL_CHN2	0x653
#define MULTIMEDIA_RPMSG_ID_BOOTANIMATION_AP_KERNEL_CHN3	0x654
#define MULTIMEDIA_RPMSG_ID_BOOTANIMATION_CP_KERNEL_CHN3	0x655
#define MULTIMEDIA_RPMSG_ID_SE04_BOOTANIMATION_AP_USR_CHN0	0x656     /* ap to cp application communication channel boot animation  detect app to player */
#define MULTIMEDIA_RPMSG_ID_SE04_BOOTANIMATION_CP_USR_CHN0	0x657    /* ap to cp application communication channel boot animation  detect app to player */
#define MULTIMEDIA_RPMSG_ID_SE04_BOOTANIMATION_AP_USR_CHN1	0x658     /* ap to cp application communication channel boot animation  detect app to player */
#define MULTIMEDIA_RPMSG_ID_SE04_BOOTANIMATION_CP_USR_CHN1	0x659    /* ap to cp application communication channel boot animation  detect app to player */
#define MULTIMEDIA_RPMSG_ID_SE04_BOOTANIMATION_AP_USR_CHN2	0x65a     /* ap to cp application communication channel boot animation  detect app to player */
#define MULTIMEDIA_RPMSG_ID_SE04_BOOTANIMATION_CP_USR_CHN2	0x65b    /* ap to cp application communication channel boot animation  detect app to player */
#define MULTIMEDIA_RPMSG_ID_SE04_BOOTANIMATION_AP_USR_CHN3	0x65c     /* ap to cp application communication channel boot animation  detect app to player */
#define MULTIMEDIA_RPMSG_ID_SE04_BOOTANIMATION_CP_USR_CHN3	0x65d    /* ap to cp application communication channel boot animation  detect app to player */

/* 0x660~0x66F for Dual SE1000 Sharing ids  with function enhancement  0x660~0x665 for  master CP→master AP→slave AP   */
#define MULTIMEDIA_RPMSG_ID_SHARING_CP_APP_MASTER_IPC				0x660
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_GLOBAL_SERVICE_MASTER_IPC		0x661
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_GLOBAL_SERVICE_MASTER_SELINK		0x662
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_GLOBAL_SERVICE_SLAVE_SELINK		0x663
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_VICAM2		0x664
#define MULTIMEDIA_RPMSG_ID_AP_SELINK_AGENT2		0x665
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_SLAVE_CONTROL	0x666
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_MASTER_CONTROL	0x667
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_SURROUND_VIEW_SLAVE_SELINK_AVM_CTRL		0x668    /* AVM slave AP selink send ctrl msg*/
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_GLOBAL_SERVICE_MASTER_SELINK_AVM_CTRL		0x669     /* AVM master AP selink recv ctrl msg*/
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_GLOBAL_SERVICE_MASTER_IPC_AVM_CTRL		0x66a     /*  AVM master AP IPC agent send ctrl msg*/
#define MULTIMEDIA_RPMSG_ID_SHARING_CP_AVM_MASTER_IPC_AVM_CTRL				0x66b     /*  AVM master CP IPC recv crtl msg*/
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_TOUCH_PRODUCER_SLAVE_SELINK_AVM_CTRL		0x66c    /*  AVM slave ap touch producer*/
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_TOUCH_AGENT_MASTER_SELINK_AVM_CTRL		0x66d    /* AVM master ap touch agent*/
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_TOUCH_AGENT_MASTER_IPC_AVM_CTRL			0x66e    /*  AVM master ap touch agent ipc*/
#define MULTIMEDIA_RPMSG_ID_SHARING_CP_TOUCH_CONSUMER_MASTER_IPC_AVM_CTRL		0x66f    /*  AVM master cp touch consumer*/

/* 0x670~0x68F for new Dual SE1000 Sharing ids */
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC2_IPC_PIPE0		0x670
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC2_IPC_PIPE1		0x671
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC2_SELINK_PIPE0		0x672
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC2_SELINK_PIPE1		0x673
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC3_IPC_PIPE0		0x674
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC3_IPC_PIPE1		0x675
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC3_SELINK_PIPE0		0x676
#define MULTIMEDIA_RPMSG_ID_SHARING_CRTC3_SELINK_PIPE1		0x677
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_VICAM3			0x678
#define MULTIMEDIA_RPMSG_ID_SHARING_AP_VICAM4			0x679
#define MULTIMEDIA_RPMSG_ID_SHARING_IPC_AGENT2			0x67a
#define MULTIMEDIA_RPMSG_ID_SHARING_IPC_AGENT3			0x67b
#define MULTIMEDIA_RPMSG_ID_SHARING_SELINK_AGENT2		0x67c
#define MULTIMEDIA_RPMSG_ID_SHARING_SELINK_AGENT3		0x67d
#define MULTIMEDIA_RPMSG_ID_SHARING_CP_VICAM2			0x67e
#define MULTIMEDIA_RPMSG_ID_SHARING_CP_VICAM3			0x67f

/*0x700-0x800 for slt test*/
#define	SELINK_RPMSG_ID_SLT_AP			0x700
#define	SELINK_RPMSG_ID_SLT_CP			0x701
#define	SELINK_RPMSG_ID_SLT_M4			0x702
#define	SELINK_RPMSG_ID_SLT_R52			0x703

/* 0x800-0x900 for sv blk */
#define	AP_CP_RPMSG_ID_SVBLK			0x800

/* 0x900-0x9FF for cluster */
#define	CLUSTER_RPMSG_ID_AUD			0x906
#define	AUD_SHR_CP2AP_RPMSG_ID_0		0x920
#define	AUD_SHR_CP2AP_RPMSG_ID_1		0x921
#define	AUD_SHR_CP2AP_RPMSG_ID_2		0x922
#define	AUD_SHR_CP2AP_RPMSG_ID_3		0x923
#define	AUD_SHR_CP2AP_RPMSG_ID_4		0x924
#define	AUD_SHR_CP2AP_RPMSG_ID_5		0x925
#define	AUD_SHR_CP2AP_RPMSG_ID_6		0x926
#define	AUD_SHR_CP2AP_RPMSG_ID_7		0x927
#define	AUD_SHR_CP2AP_RPMSG_ID_8		0x928
#define	AUD_SHR_CP2AP_RPMSG_ID_9		0x929
#define	AUD_SHR_CP2AP_RPMSG_ID_10		0x92A

#define	AUD_SHR_AP2CP_RPMSG_ID_0		0x930
#define	AUD_SHR_AP2CP_RPMSG_ID_1		0x931
#define	AUD_SHR_AP2CP_RPMSG_ID_2		0x932
#define	AUD_SHR_AP2CP_RPMSG_ID_3		0x933
#define	AUD_SHR_AP2CP_RPMSG_ID_4		0x934
#define	AUD_SHR_AP2CP_RPMSG_ID_5		0x935
#define	AUD_SHR_AP2CP_RPMSG_ID_6		0x936
#define	AUD_SHR_AP2CP_RPMSG_ID_7		0x937
#define	AUD_SHR_AP2CP_RPMSG_ID_8		0x938
#define	AUD_SHR_AP2CP_RPMSG_ID_9		0x939
#define	AUD_SHR_AP2CP_RPMSG_ID_10		0x93A

#define	AUD_SHR_KCP2UAP_RPMSG_ID_0		0x950
#define	AUD_SHR_KCP2UAP_RPMSG_ID_1		0x951
#define	AUD_SHR_KCP2UAP_RPMSG_ID_2		0x952
#define	AUD_SHR_KCP2UAP_RPMSG_ID_3		0x953
#define	AUD_SHR_KCP2UAP_RPMSG_ID_4		0x954
#define	AUD_SHR_KCP2UAP_RPMSG_ID_5		0x955
#define	AUD_SHR_KCP2UAP_RPMSG_ID_6		0x956
#define	AUD_SHR_KCP2UAP_RPMSG_ID_7		0x957
#define	AUD_SHR_KCP2UAP_RPMSG_ID_8		0x958
#define	AUD_SHR_KCP2UAP_RPMSG_ID_9		0x959
#define	AUD_SHR_KCP2UAP_RPMSG_ID_10		0x95A

#define	AUD_SHR_KAP2UCP_RPMSG_ID_0		0x960
#define	AUD_SHR_KAP2UCP_RPMSG_ID_1		0x961
#define	AUD_SHR_KAP2UCP_RPMSG_ID_2		0x962
#define	AUD_SHR_KAP2UCP_RPMSG_ID_3		0x963
#define	AUD_SHR_KAP2UCP_RPMSG_ID_4		0x964
#define	AUD_SHR_KAP2UCP_RPMSG_ID_5		0x965
#define	AUD_SHR_KAP2UCP_RPMSG_ID_6		0x966
#define	AUD_SHR_KAP2UCP_RPMSG_ID_7		0x967
#define	AUD_SHR_KAP2UCP_RPMSG_ID_8		0x968
#define	AUD_SHR_KAP2UCP_RPMSG_ID_9		0x969
#define	AUD_SHR_KAP2UCP_RPMSG_ID_10		0x96A


/* 0xA00-0xAFF for crypto/security */
#define SELINK_RPMSG_ID_CRYPTO_EP_AP0_A76_TO_M4		0xA01
#define SELINK_RPMSG_ID_CRYPTO_EP_AP0_A55_TO_M4		0xA02
#define SELINK_RPMSG_ID_CRYPTO_EP_CP_TO_M4		0xA03
#define SELINK_RPMSG_ID_CRYPTO_EP_RP_TO_M4		0xA04
#define SELINK_RPMSG_ID_CRYPTO_EP_TRUSTY_TO_M4		0xA05

#define SELINK_RPMSG_ID_CRYPTO_EP_AP0_A76_FROM_M4	0xA11
#define SELINK_RPMSG_ID_CRYPTO_EP_AP0_A55_FROM_M4	0xA12
#define SELINK_RPMSG_ID_CRYPTO_EP_CP_FROM_M4		0xA13
#define SELINK_RPMSG_ID_CRYPTO_EP_RP_FROM_M4		0xA14
#define SELINK_RPMSG_ID_CRYPTO_EP_TRUSTY_FROM_M4	0xA15

#define SELINK_RPMSG_ID_TRUSTY_EP_AP0_A76		0xA20
#define SELINK_RPMSG_ID_TRUSTY_EP_CP			0xA21

#define SELINK_RPMSG_ID_CP_STORAGE_TRUSTY		0xA30
#define SELINK_RPMSG_ID_CP_STORAGE_CP			0xA31

/* 0xB00-0xBFF for virtual CAN */
#define	SE_VCAN_RPMSG_ID_CAN			0xB00

/* 0xC00-0xCFF for ethernet module */
#define	SELINK_RPMSG_ID_RGMII0_UP		0xC02
#define	SELINK_RPMSG_ID_RGMII1_UP		0xC03

#define	LOG_TIME_AP2R52_RPMSG_ID		0x1000
#define	LOG_TIME_AP2M4_RPMSG_ID		       0x1001
#define	LOG_TIME_AP2DSP0_RPMSG_ID		0x1002
#define	LOG_TIME_AP2DSP1_RPMSG_ID		0x1003
#define	LOG_TIME_AP2CP_RPMSG_ID		       0x1004
#endif /* __SIENGINE_RPMSG_ID_H__ */
