# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Siengine Platform drivers
#
obj-$(CONFIG_SE_MAX96722) += max96722.o
obj-$(CONFIG_SE_MAX9296) += max9296.o
obj-$(CONFIG_SE_SENSOR_TYPE) += sensor.o
obj-$(CONFIG_CAMERA_AR0231) += ar0231_raw.o
obj-$(CONFIG_CAMERA_OV2311) += ov2311.o
