obj-$(CONFIG_CRYPTO_ENGINE_SE1000) += se1000/crypto_ips_internal.o
obj-$(CONFIG_CRYPTO_ENGINE_SE1000) += se1000/crypto_ips_init.o
obj-$(CONFIG_CRYPTO_ENGINE_SE1000) += se1000/crypto_ips_aes.o
obj-$(CONFIG_CRYPTO_ENGINE_SE1000) += se1000/crypto_ips_sha.o
obj-$(CONFIG_CRYPTO_ENGINE_SE1000) += se1000/ips_drv.o
obj-$(CONFIG_CRYPTO_ENGINE_SE1000) += se1000/ips_irq.o

obj-$(CONFIG_CRYPTO_ENGINE_SE1000) += se1000/crypto_smx_internal.o
obj-$(CONFIG_CRYPTO_ENGINE_SE1000) += se1000/crypto_smx_init.o
obj-$(CONFIG_CRYPTO_ENGINE_SE1000) += se1000/crypto_smx_sm3.o
obj-$(CONFIG_CRYPTO_ENGINE_SE1000) += se1000/crypto_smx_sm4.o
obj-$(CONFIG_CRYPTO_ENGINE_SE1000) += se1000/smx_drv.o
obj-$(CONFIG_CRYPTO_ENGINE_SE1000) += se1000/smx_irq.o

obj-$(CONFIG_CRYPTO_ENGINE_SE1000) += se1000/crypto_res_mgr.o
obj-$(CONFIG_CRYPTO_ENGINE_SE1000) += se1000/crypto_util.o