# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Siengine GDC driver
#
obj-$(CONFIG_SE1000_GDC) += gdc-v4l.o
obj-$(CONFIG_SE1000_GDC_DEVFREQ) += gdc-devfreq-dev.o
gdc-v4l-objs += gdc_driver.o gdc_vb2.o gdc_hw.o system_log.o

