#
# Copyright (C) 2022 Siengine Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# audio share
snd-soc-audio-share-dummy-objs := audio-share-dummy.o
obj-$(CONFIG_SND_SOC_SE1000_SHARE) += snd-soc-audio-share-dummy.o

obj-$(CONFIG_SND_SOC_SE1000_SHARE) += audio-share-card.o