# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/drivers/npu/zhouyi

aipudrv-y += zhouyi/v1.o
aipudrv-y += zhouyi/v2.o
aipudrv-y += zhouyi/v12_priv.o
aipudrv-y += zhouyi/v3.o
aipudrv-y += zhouyi/v3_priv.o
aipudrv-y += zhouyi/zhouyi.o
