#ifndef __PINCTRL_SE1000_H__
#define __PINCTRL_SE1000_H__

#include <linux/bits.h>
#include <linux/pinctrl/pinconf-generic.h>


#define PINCTRL_SE1000_CONFIG_INPUT_SCHMITT_ENABLE		PIN_CONFIG_INPUT_SCHMITT_ENABLE
#define PINCTRL_SE1000_CONFIG_DRIVE_STRENGTH			PIN_CONFIG_DRIVE_STRENGTH
#define PINCTRL_SE1000_CONFIG_PULL_UP					PIN_CONFIG_BIAS_PULL_UP
#define PINCTRL_SE1000_CONFIG_PULL_DOWN					PIN_CONFIG_BIAS_PULL_DOWN
#define PINCTRL_SE1000_CONFIG_INPUT_ENABLE				PIN_CONFIG_INPUT_ENABLE
#define PINCTRL_SE1000_CONFIG_OUTPUT_ENABLE				PIN_CONFIG_OUTPUT_ENABLE
#define PINCTRL_SE1000_CONFIG_OUTPUT					PIN_CONFIG_OUTPUT
#define PINCTRL_SE1000_CONFIG_SAFETY					(PIN_CONFIG_END + 1)
#define PINCTRL_SE1000_CONFIG_SAFE_ENABLE				(PIN_CONFIG_END + 2)

#define PINCTRL_SE1000_BIT_MUX_MAX                 4

#define PINCTRL_SE1000_BIT_SCHMITT_TRIGGER         16
#define PINCTRL_SE1000_BIT_MUX_CONFIGURATION       12
#define PINCTRL_SE1000_BIT_DRIVER_STRENGTH         8
#define PINCTRL_SE1000_BIT_PULL_DOWN               5
#define PINCTRL_SE1000_BIT_PULL_UP                 4
#define PINCTRL_SE1000_BIT_INPUT_ENABLE            3

#define PINCTRL_SE1000_SCHMITT_TRIGGER         BIT(PINCTRL_SE1000_BIT_SCHMITT_TRIGGER  )
#define PINCTRL_SE1000_MUX_CONFIGURATION       BIT(PINCTRL_SE1000_BIT_MUX_CONFIGURATION)
#define PINCTRL_SE1000_DRIVER_STRENGTH         BIT(PINCTRL_SE1000_BIT_DRIVER_STRENGTH  )
#define PINCTRL_SE1000_PULL_DOWN               BIT(PINCTRL_SE1000_BIT_PULL_DOWN        )
#define PINCTRL_SE1000_PULL_UP                 BIT(PINCTRL_SE1000_BIT_PULL_UP          )
#define PINCTRL_SE1000_INPUT_ENABLE            BIT(PINCTRL_SE1000_BIT_INPUT_ENABLE     )

#define PINCTRL_SE1000_MASK_SCHMITT_TRIGGER         (1  << PINCTRL_SE1000_BIT_SCHMITT_TRIGGER  )
#define PINCTRL_SE1000_MASK_MUX_CONFIGURATION       (3  << PINCTRL_SE1000_BIT_MUX_CONFIGURATION)
#define PINCTRL_SE1000_MASK_DRIVER_STRENGTH         (15 << PINCTRL_SE1000_BIT_DRIVER_STRENGTH  )
#define PINCTRL_SE1000_MASK_PULL_DOWN               (1  << PINCTRL_SE1000_BIT_PULL_DOWN        )
#define PINCTRL_SE1000_MASK_PULL_UP                 (1  << PINCTRL_SE1000_BIT_PULL_UP          )
#define PINCTRL_SE1000_MASK_INPUT_ENABLE            (1  << PINCTRL_SE1000_BIT_INPUT_ENABLE     )

#endif /* __PINCTRL_SE1000_H__ */