# SPDX-License-Identifier: GPL-2.0-only
#ccflags-y := -DDEBUG -O0
obj-$(CONFIG_SIENGINE_DW_MIPI_DSI) += dw-mipi-dsi-siengine.o
obj-$(CONFIG_SIENGINE_SDPIC) += se_sdpic.o
#obj-$(CONFIG_SIENGINE_PANEL) += panel-generic-dsi.o
obj-$(CONFIG_SIENGINE_DW_DPTX) += dptx/
obj-$(CONFIG_SIENGINE_SADP_VIRTUAL_DSI) += sadp_virtual_dsi_drv.o
