/* SPDX-License-Identifier: GPL-2.0.
 * sound/soc/siengine/se1000/audio_loopback/
 * Copyright (C) 2023 SiEngine Technology Co., Ltd. All rights reserved
 */

#ifndef _AUDIO_SHARE_DUMMY_IPC_H_
#define _AUDIO_SHARE_DUMMY_IPC_H_

#define OPCODE_AUD_SHARE_DATA_WRITE_DONE 0xFF01
#define OPCODE_AUD_SHARE_DATA_READ_DONE  0xFF02

#define OPCODE_AUD_MESG_FROMUS_SYNC0     0xFF03
#define OPCODE_AUD_MESG_FROMUS_SYNC1     0xFF04
#define OPCODE_AUD_MESG_FROMUS_SYNC2     0xFF05
#define OPCODE_AUD_MESG_FROMUS_SYNC3     0xFF06
#define OPCODE_AUD_MESG_FROMUS_SYNC4     0xFF07
#define OPCODE_AUD_MESG_FROMUS_SYNC5     0xFF08
#define OPCODE_AUD_MESG_FROMUS_SYNC6     0xFF09
#define OPCODE_AUD_MESG_FROMUS_SYNC7     0xFF0A
#define OPCODE_AUD_MESG_FROMUS_SYNC8     0xFF0B
#define OPCODE_AUD_MESG_FROMUS_SYNC9     0xFF0C
#define OPCODE_AUD_MESG_FROMUS_SYNC10    0xFF0D

#define OPCODE_AUD_MESG_FROMUS_UL_SYNC0  0xFF13
#define OPCODE_AUD_MESG_FROMUS_UL_SYNC1  0xFF14
#define OPCODE_AUD_MESG_FROMUS_UL_SYNC2  0xFF15
#define OPCODE_AUD_MESG_FROMUS_UL_SYNC3  0xFF16
#define OPCODE_AUD_MESG_FROMUS_UL_SYNC4  0xFF17
#define OPCODE_AUD_MESG_FROMUS_UL_SYNC5  0xFF18
#define OPCODE_AUD_MESG_FROMUS_UL_SYNC6  0xFF19
#define OPCODE_AUD_MESG_FROMUS_UL_SYNC7  0xFF1A
#define OPCODE_AUD_MESG_FROMUS_UL_SYNC8  0xFF1B
#define OPCODE_AUD_MESG_FROMUS_UL_SYNC9  0xFF1C
#define OPCODE_AUD_MESG_FROMUS_UL_SYNC10 0xFF1D

#define OPCODE_AUD_MESG_TOUS_SYNC0       0xFF20
#define OPCODE_AUD_MESG_TOUS_SYNC1       0xFF21
#define OPCODE_AUD_MESG_TOUS_SYNC2       0xFF22
#define OPCODE_AUD_MESG_TOUS_SYNC3       0xFF23
#define OPCODE_AUD_MESG_TOUS_SYNC4       0xFF24
#define OPCODE_AUD_MESG_TOUS_SYNC5       0xFF25
#define OPCODE_AUD_MESG_TOUS_SYNC6       0xFF26
#define OPCODE_AUD_MESG_TOUS_SYNC7       0xFF27
#define OPCODE_AUD_MESG_TOUS_SYNC8       0xFF28
#define OPCODE_AUD_MESG_TOUS_SYNC9       0xFF29
#define OPCODE_AUD_MESG_TOUS_SYNC10      0xFF2A

#define OPCODE_AUD_MESG_TOUS_UL_SYNC0    0xFF30
#define OPCODE_AUD_MESG_TOUS_UL_SYNC1    0xFF31
#define OPCODE_AUD_MESG_TOUS_UL_SYNC2    0xFF32
#define OPCODE_AUD_MESG_TOUS_UL_SYNC3    0xFF33
#define OPCODE_AUD_MESG_TOUS_UL_SYNC4    0xFF34
#define OPCODE_AUD_MESG_TOUS_UL_SYNC5    0xFF35
#define OPCODE_AUD_MESG_TOUS_UL_SYNC6    0xFF36
#define OPCODE_AUD_MESG_TOUS_UL_SYNC7    0xFF37
#define OPCODE_AUD_MESG_TOUS_UL_SYNC8    0xFF38
#define OPCODE_AUD_MESG_TOUS_UL_SYNC9    0xFF39
#define OPCODE_AUD_MESG_TOUS_UL_SYNC10    0xFF3A

#define SNDRV_COMP_IOCTL_LOOP_DAI_HW_FORWARD _IOW('A', 0x100, int)
#define SNDRV_COMP_IOCTL_LOOP_DAI_READY_STATUS	_IOR('A', 0x101, int)

typedef struct dummy_rpmsg_payload {
	uint32_t		opcode;
	uint32_t		offset;
} dummy_rpmsg_payload_t;

#endif
