#
# Copyright (C) 2023 SiEngine Technology Co., Ltd. All rights reserved
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

# platform driver
snd-soc-se1000-loopback-objs := se1000-share-loopback.o audio-share-dummy-loop-dai.o
obj-$(CONFIG_SND_SOC_SE1000_LOOPBACK) += snd-soc-se1000-loopback.o
